Django API
CodeForAfricaLabs/HealthTools.API pull request #11
Opened 2017-07-14 12:33 UTC by Gathondu

#### What does this PR do?
It refactors the healthtools api from a flask based api to a django based api
It refactors the tests to work with django api
Adds health facilities and nhif endpoints to the api
#### Description of Task to be completed?
[HTools API] Use Django rest framework
#### How should this be manually tested?
run `nosetests --nocapture`
#### Any background context you want to provide?
The initial codebase was flask geared but due to new requirement and the versatility of django rest framework, we decided to refactor the codebase.

2017-07-14 12:33 UTC, Gathondu commented
@DavidLemayian

2017-07-18 16:08 UTC, DavidLemayian requested changes

2017-07-18 16:08 UTC, DavidLemayian commented on healthtools_api/healthtools_api/settings.py
> +SECRET_KEY = '%o#_bhrnzhr6$_sblamdq#=z0d(&+kr_3#ev^n$d=4e02z%jvj'
@Gathondu Should this not be in .env?

2017-07-18 16:08 UTC, DavidLemayian commented on healthtools_api/healthtools_api/settings.py
> +DEBUG = True
Let's have this .env

2017-07-21 08:23 UTC, closed without merging