Added Health facilities view to the Api
CodeForAfricaLabs/HealthTools.API pull request #15
Opened 2017-08-21 14:12 UTC by Awinja-Andela

#### This Pull Request Introduces the health facilities Api View 

#### Description of Task to be completed:
The task required writing tests for health facilities and its end points.

#### Manual testing:
You can manually test it by running ```nosetests``` or ```python test_health_facilities.py```

#### Relevant Trello stories?
[HTools API] Add Health Facilities view

2017-08-21 18:03 UTC, DavidLemayian requested changes
Let's also git-ignore `.DS_Store`.

Does this work with SMS?

2017-08-21 18:03 UTC, DavidLemayian commented on healthtools_ke_api/__init__.py
> +app.register_blueprint(health_facilities_api, url_prefix='/health_facilities')
This should be `health-facilities`. With a `-` instead of `_`.

2017-08-21 18:03 UTC, DavidLemayian commented on healthtools_ke_api/views/search.py
> +        keywords = ['dr', 'dr.', 'doctor', 'nurse', 'co', 'c.o.', 'c.o', 'clinical officer','health facility']
What other derivatives for "health facilities" can we think about?

2017-08-22 08:37 UTC, Awinja-Andela commented on healthtools_ke_api/__init__.py
> +app.register_blueprint(health_facilities_api, url_prefix='/health_facilities')
@DavidLemayian Changed.

2017-08-22 12:50 UTC, Awinja-Andela commented on healthtools_ke_api/views/search.py
> +        keywords = ['dr', 'dr.', 'doctor', 'nurse', 'co', 'c.o.', 'c.o', 'clinical officer','health facility']
@DavidLemayian hf and h.f.
I have added these two.

2017-08-22 14:57 UTC, DavidLemayian commented on healthtools_ke_api/views/search.py
> +        keywords = ['dr', 'dr.', 'doctor', 'nurse', 'co', 'c.o.', 'c.o', 'clinical officer','health facility']
@Awinja-Andela Hmm.. I don't see them added here.. "facility" as well perhaps?

2017-08-22 14:57 UTC, DavidLemayian commented on healthtools_ke_api/__init__.py
> +app.register_blueprint(health_facilities_api, url_prefix='/health_facilities')
@Awinja-Andela I can't see the change reflected on this PR..

2017-08-22 20:03 UTC, DavidLemayian requested changes

2017-08-22 20:03 UTC, DavidLemayian commented on healthtools_ke_api/views/search.py
> +        keywords = ['dr', 'dr.', 'doctor', 'nurse', 'co', 'c.o.', 'c.o','hf', 'h.f', 'h.f.', 'clinical officer','health facility']
Let's cluster these appropriately i.e `'clinical officers'` should come before the health facility alternatives. We don't simply do.. we do well.

2017-08-22 20:03 UTC, DavidLemayian commented on manage.py
> +    app.run(debug=True)
This should be environment settable.

2017-08-24 06:58 UTC, DavidLemayian requested changes

2017-08-24 06:58 UTC, DavidLemayian commented on .gitignore
> +.DS_Store
This should be deleted and gitignored from every folder.

Please make sure it doesn't come through to the PR.

2017-08-30 12:52 UTC, closed without merging